### ISSUE TITLE
Unable to start vite after 0.9.0

### ISSUE THREAD

**Issue by eMerzh** [cometkim/vite-plugin-relay-lite#180]
Hey, 

Thanks for your continuous work on this 👋 
just letting you know that upgrading to 0.9.0 lead to being unable to start vite, 
it launched then get stuck after generating the relay files, 
probably not passing the hand to the rest of the process 

i suspect this one https://github.com/cometkim/vite-plugin-relay-lite/commit/b2dd74f2e9b250ffea9a5fba2d806bc97b3d5ffa#diff-a9837633f28b4c63886d9fe0a38b8dc2dab4baf078a2401d61b3cbade96efe32L51

**Comment by cometkim** [comment]
will be fixed in v0.9.1. perhaps I missed something with signaling

**Comment by eMerzh** [comment]
thanks for the quick actions 🙌  ❤️  ...let me know if i can help
