### ISSUE TITLE
Failed to read `relay` field in `package.json`

### ISSUE THREAD

**Issue by tonyfromundefined** [cometkim/vite-plugin-relay-lite#200]
## Issue
I found an issue where configuration files such as `relay.config.json` are read correctly, but the `relay` field within `package.json` is not read correctly.

**Comment by cometkim** [comment]
I guess you're using monorepo?

**Comment by cometkim** [comment]
The config loader currently rely on the [cosmiconfig](https://github.com/cosmiconfig/cosmiconfig), but now I'm planning to replace it by own loader and I won't support `package.json` fields though.
