### ISSUE TITLE
Update Vite peer dependency to including ^3.0.0

### ISSUE THREAD

**Issue by devunt** [cometkim/vite-plugin-relay-lite#4]
Current package indicates `"vite": "^2.0.0"` as its peer dependency, but since it is working well and comprehensively tested in Vite 3.x as well, I suggest modifying it to `"vite": "^2.0.0 || ^3.0.0"`.

As of now this package constantly showing unmet peer dependency warnings with Vite 3.x.

**Comment by gajus** [comment]
@cometkim Could we get this added?

**Comment by cometkim** [comment]
@devunt @gajus Yep, I just published it at v0.3.0

**Comment by gajus** [comment]
Thank you!
