### ISSUE TITLE
Few The definition of Fragment appears to have changed. Run `relay-compiler`

### ISSUE THREAD

**Issue by eMerzh** [cometkim/vite-plugin-relay-lite#53]
Hello @cometkim 👋 

I notice a few errors like this:
>The definition of 'SpaceGroup_spaceGroup' appears to have changed. Run `relay-compiler`
of course runing the compiler or the plugin doesn't change anything.

looking at the generated file, it seems that the file is well generated.

not sure where this could come from...

i noticed that it might be some sort of difference between the "hash" and the `@generated SignedSource`
and the plugin alterning between one and the other? but this is a wild guess and i'm really unsure... 

if you have any precise idea ? 

thanks 🙏

**Comment by eMerzh** [comment]
ok .. i think i'm on the path ... 
babel relay produce a different md5 because it produces a different string representation of the fragment ...
we used graphql 16.X in our tool and babel uses https://github.com/facebook/relay/blob/main/packages/babel-plugin-relay/package.json#L22 
then i presume that relay-compiler have the same text representation ...

not sure how to fix that without downgrading graphql on our side 🤔  

maybe there's a way to silence them?

**Comment by cometkim** [comment]
Hmm can you share minimal reproduction, the fragment at least? Let me dig in

**Comment by eMerzh** [comment]
hum... i can try... but its on a closed codebase atm

**Comment by eMerzh** [comment]
Hello @cometkim ... long time 😬 
I took a bit of time to look at this 

i have query looking like this
```js
const query = graphql`
	query MentionSelectQuery {
		me {
			mention(
				query: ""
				storyId: ""
				groups: false
				users: false
				teams: false
				exclude: []
			) {
				__typename
			}
		}
	}
```

relay compiler extract it in MentionQuery.graphql.ts as

```
query MentionSelectQuery {\n  me {\n    mention(query: \"\", storyId: \"\", groups: false, users: false, teams: false, exclude: []) {\n      __typename\n      ... on Node {\n        __isNode: __typename\n        id\n      }\n    }\n    id\n  }\n}\n
```

this is with 
```jsonc
{
//...
"graphql": "16.8.1",
 "vite-plugin-relay-lite": "0.6.0",
}

```

and vite-plugin-relay-lite (graphql) is generating it like this
```graphql
query MentionSelectQuery {
  me {
    mention(
      query: ""
      storyId: ""
      groups: false
      users: false
      teams: false
      exclude: []
    ) {
      __typename
    }
  }
}
```
==> md5 `2f6583786d56842362dba14c08d2bb78`

now if i downgrade graphql to 15.0.0 for example, then 
vite-plugin-relay-lite  generate
```graphql
query MentionSelectQuery {
  me {
    mention(query: "", storyId: "", groups: false, users: false, teams: false, exclude: []) {
      __typename
    }
  }
}
```
=> md5 `3742279b5e660168bd0c416c594e14c7`


Relay compiler is generating `3742279b5e660168bd0c416c594e14c7` in hash

**Comment by cometkim** [comment]
Relay compiler generates different hash... sounds like breaking

I will look into it this week

**Comment by cometkim** [comment]
This seems caused by https://github.com/graphql/graphql-js/pull/2797, as this potentially causes hash change like this, it had to be introduced as a breaking change :/

**Comment by cometkim** [comment]
Anyway, the graphql-js takes precedence here as the reference implementation, so I think it is a bug in the relay compiler.

This appears to have already been reported on the issue tracker.

https://github.com/facebook/relay/issues/4226

**Comment by eMerzh** [comment]
ooh, nice, thanks for the heads up
