### ISSUE TITLE
Broken Tag detection

### ISSUE THREAD

**Issue by eMerzh** [cometkim/vite-plugin-relay-lite#72]
Hello @cometkim , while trying to update to v.0.6

I noticed an issue in the new query detection

we had a (ok, strange)
```js
	const result = useFragment(
		spaceOrGroup.__typename === 'Space'
			? graphql`
					fragment SearchResult_space on Space {
						name
						thumbnailImage
						color
						spaceGroup {
							name
						}
					}
			  `
			: graphql`
					fragment SearchResult_spaceGroup on SpaceGroup {
						name
						color
						thumbnailImage
					}
			  `,
		spaceOrGroup,
	)
```
but those weren't recognized as needed ( with prod builds, ok with dev)
i'have extracted the fragments and now it's ok

**Comment by cometkim** [comment]
Hey @eMerzh 

Can you confirm if this issue is still reproducible?

**Comment by cometkim** [comment]
Never mind, i got the case

**Comment by eMerzh** [comment]
Very nice,  thanks 👍
