### ISSUE TITLE
Should I still use `babel-plugin-relay/macro`?

### ISSUE THREAD

**Issue by FezVrasta** [cometkim/vite-plugin-relay-lite#78]
Should I still use `babel-plugin-relay/macro`? Will the plugin replace it with its own version? Or should I do something different?

**Comment by cometkim** [comment]
This project replaces the babel plugin with its own code. So you don't need to setup the babel plugin or babel macros.

**Comment by FezVrasta** [comment]
Thanks, what should I import in order to use the `graphql` tagged function then?

**Comment by FezVrasta** [comment]
Ah I guess I have to use it from `react-relay`?

```
import { graphql } from 'react-relay';

const GetPostQuery = graphql`
  query AppGetPostQuery($id: ID!) {
    Post(id: $id) {
      id
      title
      views
      user_id
    }
  }
`;
```

**Comment by cometkim** [comment]
Well, no matter what it is from, any tag with the name `graphql` will be handled
