### ISSUE TITLE
Broken parsing with comments

### ISSUE THREAD

**Issue by eMerzh** [cometkim/vite-plugin-relay-lite#94]
Sorry @cometkim  /o\ 

i've noticed some new issues here with https://github.com/cometkim/vite-plugin-relay-lite/commit/dd801c563a4f0a40599491b21b4a9b2ac21e8a68#diff-1abfb4d434506bafbdaf2c4b6274e292de3eb39ddf3845fc3b970fa5daf8fc00R30

i got : 

```js
// When creating a story from a space
const spaceFragment = graphql`
	fragment useStoryEditor_space on Space {
		id
		name
		...SpaceSquare_space
		spaceGroup {
			# Needed for the space pre-selection
			name
			id
		}
		actions {
			postStory
			postDraftStory
		}
		...StorySpaceDialog_space
	}
`
```

thus prefix looks like 
>   prefix: '\n// When creating a story from a space\n\nconst spaceFragment = ',

and thus lead to unparsed query, 
the remove comment part doesn't really work here.

I guess it's better to leave the ternary as it was than this .. (this seems more legit usage)

**Comment by cometkim** [comment]
> thus prefix looks like
>
> > prefix: '\n// When creating a story from a space\n\nconst spaceFragment = ',

This is unintentional. `prefix` should only include an adjacent line. Can you please file a PR with a test that reproduces that?

**Comment by eMerzh** [comment]
tried my best for a repro... anyways, many thanks for looking into this :) 
it's probably not your use case, but it helps me quite a lot 

:)

**Comment by cometkim** [comment]
No prob, It actually helps me too. I was too naive when implementing this :sweat_smile:

**Comment by cometkim** [comment]
@eMerzh can you try v0.7.1 just released?

**Comment by eMerzh** [comment]
arg, i really thought it was good .... but there are still issues, with kinda legit files :( 

i got this file
```jsx
import { graphql } from 'react-relay'

import createQueryRenderer from 'libs/relay/createQueryRenderer'
import environment from 'libs/relay/environment'

import Space from './Space'

export default createQueryRenderer(
	Space,
	graphql`
		query SpaceQueryRendererQuery($spaceId: Int!) {
			space(slug: $spaceId) {
				... on Space {
					...Space_space
				}
			}
		}
	`,
	{
		environment,
		variables: ({ spaceId }) => ({ spaceId }),
	},
)
```

which is translated to 
```
...

import Space from "/modules/app/layouts/components/Drawer/Space.jsx";
export default _c = createQueryRenderer(Space, graphql`
...
``` 

but for the moment i can't really do a test case 🤔 
i'll try tomorrow maybe

**Comment by cometkim** [comment]
Ah you use tabs instead of spaces right?

**Comment by cometkim** [comment]
Then v0.7.3 :sweat_smile: I really need to become patient to release

**Comment by eMerzh** [comment]
ahaha, those release helps me test it 😅 

found a new issue 😬 

sometimes eventhough the old relay way is written with distinct lines, the source going through the plugin put them in one line, breaking the detection
like this
```js
    export default createQueryRenderer(Space, graphql`
		query SpaceQueryRendererQuery($spaceId: Int!) {
			space(slug: $spaceId) {
				... on Space {
					...Space_space
				}
			}
		}
	  `,  { variables: () => ({})});
```

**Comment by cometkim** [comment]
😇

**Comment by eMerzh** [comment]
Thanks again... it's better, but i still have some issues :

i had query in if else but i rewrote those to be more top level query but queried with the if/else...

but then i got this :
```
	const relay = useQuery(
		// extra fields are used to fill space select like AnalyticsSpaces_me
		/* eslint-disable relay/unused-fields */
		graphql`
			query ActiveSpacesGraphQuery($fromDate: IsoDateTime!, $toDate: IsoDateTime!, $team: ID) {
				instance {
					statistics {
```
which is not peeerfect, but kinda legit i would say...
but those start to be hard to grasp with regex :( in fact it seems the 0.6 method seems to work better, eventough there were some gotcha too ofc

**Comment by cometkim** [comment]
Multiline comments are intentionally unhandled, as I mentioned from README. 

However, the use case (notations) seems can be reasonably handled

But you are right. It would never be perfect due to its RegExp based approach

**Comment by cometkim** [comment]
But trust me. The current complexity level of the RegExp pattern is not a big deal to me at all (I do use RegExp even more 😅)

I just need more test suites

**Comment by cometkim** [comment]
![image](https://github.com/cometkim/vite-plugin-relay-lite/assets/9696352/b3539ac6-641d-4978-bb9c-3f4424495fc9)

The query you reported should currently work fine. If it doesn't, do you have any comment string that includes `//` somewhere in the `graphql` tagged literal?

**Comment by cometkim** [comment]
Fixed more case here https://github.com/cometkim/vite-plugin-relay-lite/commit/a3aef3e143e43d8fad7420b860c70d0160b6c638

**Comment by eMerzh** [comment]
Thanks i'll check this.
In the mean time, i fixed all the code in my repo, and added a CI step to detect any graphql` in the resulting code /o\

**Comment by cometkim** [comment]
> In the mean time, i fixed all the code in my repo, and added a CI step to detect any graphql` in the resulting code /o\

ohhh that's actually a great idea. I will make it as vite plugin right now

**Comment by cometkim** [comment]
I thought about it again. If we can safely remove the import statement for the graphql tag after the transform, referencing it will cause bundler errors.

I could add a new plugin entry for warning transform error, but I'm not sure it would be more useful than it.

**Comment by cometkim** [comment]
@eMerzh you can try [v0.8.0](https://github.com/cometkim/vite-plugin-relay-lite/releases/tag/vite-plugin-relay-lite%400.8.0)

Enabling `omitTagImport` makes the Vite build fail if there are any missing transforms

**Comment by eMerzh** [comment]
wow thanks, fast 😎 

i got 
```js
		relay({
			codegen: env === 'development',
			module: 'esmodule',
			omitTagImport: true, 
		}),
		```
but the build finishes 🤔 
and  grep 'graphql`' dist/*.js give me results... 
do i do something wrong?

**Comment by cometkim** [comment]
Enabling the option will remove the `graphql` tag import.

Code that uses the `graphql` tag then raises `ReferenceError`, which is a runtime error. I was thinking that it would be confirmed at build time as well...  It was not, because the bundler is responsible for statically analyzing only the module graph.

Simply checking the <code>graphql\`</code> is something I wanted to avoid because it would result in a false positive in comments.


Well... Let me think more. I can still add a validator, but it must be stricter than the plugin itself.
